<?php exit;
'well_shield_setting' => '過濾關鍵詞',
'well_shield_username_limit_character' => '用戶名必須 1 個以上字符',
'well_shield_username_format_only_english' => '請使用英文或數字',
'well_shield_contain_keyword' => '包含敏感詞',
'well_shield_input_tips' => '來點有營養的內容唄',
'well_shield_a' => '過濾鏈接',
'well_shield_a_tips' => '過濾內容中的a標籤',
'well_shield_username' => '註冊過濾',
'well_shield_username_tips' => '註冊賬戶中包含關鍵詞將不能註冊',
'well_shield_username_limit' => '註冊限制',
'well_shield_username_limit_tips' => '限制使用英文或數字註冊賬戶',
'well_shield_keyword' => '需要限制的關鍵詞。 “|” 豎線切割',
'well_shield_content' => '內容過濾',
'well_shield_content_tips' => '內容中包含關鍵詞將不能發表',
'well_shield_ip' => '屏蔽IP',
'well_shield_ip_tips' => '被屏蔽的IP將不能訪問網站',
'well_shield_ip_fmt' => '每行一個IP',
?>