<?php exit;
'well_shield_setting' => '过滤关键词',
'well_shield_username_limit_character' => '用户名必须 1 个以上字符',
'well_shield_username_format_only_english' => '请使用英文或数字',
'well_shield_contain_keyword' => '包含敏感词',
'well_shield_input_tips' => '来点有营养的内容呗',
'well_shield_a' => '过滤链接',
'well_shield_a_tips' => '过滤内容中的a标签',
'well_shield_username' => '注册过滤',
'well_shield_username_tips' => '注册账户中包含关键词将不能注册',
'well_shield_username_limit' => '注册限制',
'well_shield_username_limit_tips' => '限制使用英文或数字注册账户',
'well_shield_keyword' => '需要限制的关键词。“|” 竖线切割',
'well_shield_content' => '内容过滤',
'well_shield_content_tips' => '内容中包含关键词将不能发表',
'well_shield_ip' => '屏蔽IP',
'well_shield_ip_tips' => '被屏蔽的IP将不能访问网站',
'well_shield_ip_fmt' => '每行一个IP',
?>