<?php exit;
'well_shield_setting' =>'Filter keywords',
'well_shield_username_limit_character' =>'Username must have more than 1 characters',
'well_shield_username_format_only_english' =>'Please use English or numbers',
'well_shield_contain_keyword' =>'Contains sensitive words',
'well_shield_input_tips' =>'Come some nutritious content',
'well_shield_a' =>'Filter links',
'well_shield_a_tips' =>'URL link in filter content',
'well_shield_username' =>'Registration filtering',
'well_shield_username_tips' =>'The registered account contains keywords and will not be able to register',
'well_shield_username_limit' =>'Registration limit',
'well_shield_username_limit_tips' =>'Limit the use of English or digital registered accounts',
'well_shield_keyword' =>'Keywords that need to be restricted. "|" Vertical line cutting',
'well_shield_content' =>'Content filtering',
'well_shield_content_tips' =>'Content containing keywords will not be published',
'well_shield_ip' =>'Shield IP',
'well_shield_ip_tips' =>'The blocked IP will not be able to access the website',
'well_shield_ip_fmt' =>'One IP per line',
?>